#ifndef BIT_MATH_H_INCLUDED
#define BIT_MATH_H_INCLUDED

#define SETBIT(REGISTER, BIT) (REGISTER |= (1<<BIT))
#define CLRBIT(REGISTER, BIT) (REGISTER &= ~(1<<BIT))
#define TOGBIT(REGISTER, BIT) (REGISTER ^= (1<<BIT))
#define GETBIT(REGISTER, BIT) ((REGISTER>>BIT)&1)

#endif // BIT_MATH_H_INCLUDED
