#ifndef SEVENSEGMENT_CONFIG_H_INCLUDED
#define SEVENSEGMENT_CONFIG_H_INCLUDED

#define SEVENSEGMENT_DATA_PORT DIO_PORTD
#define SEVENSEGMENT_CONTROL_PORT DIO_PORTB
#define SEVENSEGMENT_EN0 PIN2
#define SEVENSEGMENT_EN1 PIN3

#endif // SEVENSEGMENT_CONFIG_H_INCLUDED
